apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    name: proxy
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 31366
    - name: https
      port: 443
      nodePort: 30168
  selector:
    name: proxy
